production:
  clients:
    default:
      uri:  <%= ENV["MONGO_URL"] %>
      options:
        server_selection_timeout: 5
        connect_timeout: 15

development:
  clients:
    default:
      database: empw_api_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1

test:
  clients:
    default:
      database: empw_api_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
